/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kunalsagar.kafkaapp;

import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.StringSerializer;

import java.util.Properties;

public class Producer {

    public static void main(String[] args) {

        String bootstrapServer = "KunalSagar1d.mylabserver.com:9092";

        // Producer configs
        Properties properties = new Properties();
        properties.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServer);
        properties.setProperty(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
        properties.setProperty(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());

        // Create Producer
        KafkaProducer<String, String> producer = new KafkaProducer<String, String>(properties);


        // Create producer record
        ProducerRecord<String, String> record = new ProducerRecord<String, String>("test", "Hello Kafka! this is KRS!");

        // send data
        producer.send(record);

        // flush data
        producer.flush();

        // close producer
        producer.close();

        System.out.println("Message sent!");
    }
}
